dofile('flashmod.lc')
dofile('LLbin.lc')

local server = flashMod("server")
server:init(file)
local tcp = net.createServer(net.TCP)
tcp:listen(80, function(conn)
  conn:on("receive", function(conn, payload)
    server:receiver(conn, payload)
  end)
end)
